sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"

before_install:
 - chmod +x mvnw

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn package docker:build -DpushImage"
  skip_cleanup: true
  on:
    tags: true